# Nome do nosso workflow. Aparecerá na aba "Actions" do seu repositório GitHub.
name: Deploy to Google Cloud Run (Multi-Region)

# Define o gatilho: este workflow rodará toda vez que houver um push para a branch 'main'.
on:
  push:
    branches:
      - main

# Define as variáveis de ambiente que usaremos em todo o workflow.
env:
  # AJUSTE DA INDENTAÇÃO
  PROJECT_ID: marcia-art
  REPO_NAME: marcia-art-repo

  # AJUSTE CRUCIAL: Definimos regiões separadas
  BACKEND_REGION: southamerica-east1 # São Paulo (Onde a API fica)
  FRONTEND_REGION: us-central1 # Nova Região (Onde o Web/Domínio mapeia)

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      # 1. Clona o seu repositório para a máquina virtual.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Autentica no Google Cloud usando a chave secreta.
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # 3. Configura o gcloud CLI para usar nosso projeto.
      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      # 4. Configura o Docker para AMBAS as regiões de repositório.
      - name: Configure Docker (Multi-Region)
        run: |
          gcloud auth configure-docker ${{ env.BACKEND_REGION }}-docker.pkg.dev
          gcloud auth configure-docker ${{ env.FRONTEND_REGION }}-docker.pkg.dev

      - name: Create Service Account Key File for Backend
        run: echo '${{ secrets.GCP_SA_KEY }}' > server/serviceAccountKey.json

      # --- DEPLOY DO BACKEND (SERVER - SOUTHAMERICA-EAST1) ---
      - name: Build and Push Backend Image (SAE1)
        run: |
          docker build -t ${{ env.BACKEND_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/server-image:${{ github.sha }} ./server
          docker push ${{ env.BACKEND_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/server-image:${{ github.sha }}

      - name: Deploy Backend to Cloud Run (SAE1)
        run: |
          gcloud run deploy marcia-art-api \
            --image ${{ env.BACKEND_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/server-image:${{ github.sha }} \
            --region ${{ env.BACKEND_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 3001

      # --- DEPLOY DO FRONTEND (CLIENT - US-CENTRAL1) ---
      # **ATENÇÃO:** O Build/Push do Frontend usa o repositório USC1 que criamos
      - name: Build and Push Frontend Image (USC1)
        run: |
          docker build -t ${{ env.FRONTEND_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/marcia-art-repo-${{ env.FRONTEND_REGION }}/client-image:production-us ./client
          docker push ${{ env.FRONTEND_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/marcia-art-repo-${{ env.FRONTEND_REGION }}/client-image:production-us

      - name: Deploy Frontend to Cloud Run (USC1)
        run: |
          gcloud run deploy marcia-art-web \
            --image ${{ env.FRONTEND_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/marcia-art-repo-${{ env.FRONTEND_REGION }}/client-image:production-us \
            --region ${{ env.FRONTEND_REGION }} \
            --platform managed \
            --allow-unauthenticated
